apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-app-dev
  labels:
    app: my-go-app
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-go-app
      environment: development
  template:
    metadata:
      labels:
        app: my-go-app
        environment: development
    spec:
      containers:
      - name: my-go-app
        image: huitingfeng/project-devops-cd:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Never



---

apiVersion: v1
kind: Service
metadata:
  name: my-go-app-service-dev
  labels:
    app: my-go-app
    environment: development
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
spec:
  # type: NodePort
  selector:
    app: my-go-app
    environment: development
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      # nodePort: 30007  # minikube ip: 192.168.49.2



---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-go-app-ingress
spec:
  rules:
  - http:
      paths:
      - path: /whoami
        pathType: Prefix
        backend:
          service:
            name: my-go-app-service-dev
            port:
              number: 80