apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-app-prod
  labels:
    app: my-go-app
    environment: production
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: my-go-app
      environment: production
  template:
    metadata:
      labels:
        app: my-go-app
        environment: production
    spec:
      containers:
      - name: my-go-app
        image: huitingfeng/project-devops-cd:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  name: my-go-app-service-prod
  labels:
    app: my-go-app
    environment: production
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
spec:
  selector:
    app: my-go-app
    environment: production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
