apiVersion: v1
data:
  alert.rules.yaml: |-
    groups:
    - name: kubernetes-pods
      rules:
      - alert: K8sPodNotRunning
        expr: kube_pod_status_phase{phase=~"Pending|Failed|Unknown"} > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-running state for more than 5 minutes."
          description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is {{ $labels.phase }} for more than 5 minutes."

      - alert: TestAlert
        expr: vector(1)
        for: 15s
        labels:
          severity: 'warning'
        annotations:
          summary: "This is a test alert"
          description: "If you're seeing this, the alerting pipeline works."
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: alert-rules
